version: "3"

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 5001:5000
    expose:
      - "5000"
    env_file:
      - .env
  nginx:
    image: webapp-nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - web