version: "3"
services:
  webapp:
    container_name: sh-web
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./shweb:/opt/webapp/shweb
    env_file:
      - .env.docker
