version: "3"

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    expose:
      - "5000"
    env_file:
      - .env
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web