version: "3"

services:
  shweb:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    expose:
      - "5000"
    env_file:
      - .env
    networks:
      - bc30138-net

networks:
  bc30138-net:
    external: true