version: "3"

services:
  shweb:
    restart: always
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    expose:
      - "5000"
    env_file:
      - .env
    networks:
      - bc30138-net

networks:
  bc30138-net:
    external: true