name: Deploy
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "deploy"
        run: |
          ssh-add - <<< "${{ secrets.SERVER_KEY }}"
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} -f '
              cd sh-web
              ls
          '