name: Deploy
on: [workflow_dispatch]
env:
  PRIVATE_KEY_PATH: private.key 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: "create ssh key"
        env:
            SSH_PRIVATE_KEY: ${{secrets.SERVER_KEY}}
            SSH_KNOWN_HOSTS: ${{secrets.SERVER_KNOWN_HOSTS}}
        shell: bash
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > $PRIVATE_KEY_PATH
          sudo chmod 600 $PRIVATE_KEY_PATH
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      - name: "use ssh"
        shell: bash
        run: |
          ls
          ssh -i $PRIVATE_KEY_PATH ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} -f '
              docker kill $(docker ps -q)
              docker container prune -f
              docker image prune -a -f
              rm -rf sh-web
          '

