name: Deploy
on: [workflow_dispatch]
env:
  PRIVATE_KEY_PATH: private.key 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "create ssh key"
        env:
            SSH_PRIVATE_KEY: ${{secrets.SERVER_KEY}}
            SSH_KNOWN_HOSTS: ${{secrets.SERVER_KNOWN_HOSTS}}
        shell: bash
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > $PRIVATE_KEY_PATH
          sudo chmod 600 $PRIVATE_KEY_PATH
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
      - name: "use ssh"
        shell: bash
        run:
          ssh -i $PRIVATE_KEY_PATH ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} -f '
              cd sh-web;
              ls;
          '
        
          